memos/memos/models/MemoHistory.py
from datetime import datetime
from memos import db
from memos.models.User import User
from memos.models.MemoActivity import MemoActivity
from flask import current_app
from flask_login import current_user

class MemoHistory(db.Model):
    id = db.Column(db.Integer, primary_key=True)

    memo_id = db.Column(db.Integer, db.ForeignKey('memo.id'))
    memo_ref = db.Column(db.String(48))
    date = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    memo_activity = db.Column(db.Enum(MemoActivity))      # For some reason the attribute names "activity" and "action" are illegal
    ref_user_id = db.Column(db.String(120), db.ForeignKey('user.username'),nullable=False)

    @staticmethod
    def activity(memo=None,memo_activity=None,user=None):
        if user is not None:
            userid = user.username
        elif current_user.is_authenticated:
            userid = current_user.username
        else:
            userid = '0' # or 'system ' But you should first create the default user system; then this system will work.
        current_app.logger.info(f"activity={memo_activity} memo={memo} memoid={memo.id} user={user}")
   
        if memo_activity != MemoActivity.Cancel:
            mh = MemoHistory(memo_id=memo.id,memo_ref=f"{memo}",memo_activity=memo_activity,ref_user_id=userid)
        else:
            # Update all of the memo_id's of this one to NULL
            MemoHistory.query.filter_by(memo_id=memo.id).update(dict(memo_id=None))
            mh = MemoHistory(memo_id=None,memo_ref=f"{memo}",memo_activity=memo_activity,ref_user_id=userid)
            
        
        db.session.add(mh)

            
    @staticmethod
    def get_history(memo_ref=None,memo=None,page=1,pagesize=None):
        return MemoHistory.query.order_by(MemoHistory.id.desc()).paginate(page = page,per_page=pagesize)

memos/memos/memos/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, FileField,BooleanField,HiddenField
from wtforms.validators import DataRequired,ValidationError
from memos.models.User import User
from memos.models.User import User
from memos.models.Memo import Memo
from wtforms.fields import DateField
from memos.models.MemoFile import MemoFile
from memos.models.MemoSignature import MemoSignature
from flask import current_app
class MemoForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    keywords = StringField('Keywords')
    distribution = StringField('Distribution')
    signers = StringField('Signers')
    references = StringField('References')
    confidential = BooleanField('Confidential?')

    username = HiddenField('username')
    memo_number = HiddenField('memo_number')
    memo_version = HiddenField('memo_version')

    memodoc1 = FileField('Memo')
    memodoc2 = FileField('Memo')
    memodoc3 = FileField('Memo')
    memodoc4 = FileField('Memo')
    memodoc5 = FileField('Memo')

    submit = SubmitField('Submit')
    save   = SubmitField('Save',render_kw={'formnovalidate': True})
    cancel = SubmitField('Cancel',render_kw={'formnovalidate': True})

    def validate_distribution(self, distribution):
        users = User.valid_usernames(distribution.data)
        if len(users['invalid_usernames']) > 0:
            raise ValidationError(f'Invalid users {users["invalid_usernames"]}')

    def validate_signers(self, distribution):
        users = User.valid_usernames(distribution.data)
        if users['non_users']:
            raise ValidationError(f'Invalid users {users["invalid_usernames"]} or email addresses specified.')
    
    def validate_references(self,references):
        current_app.logger.info(f"References = {references.data}")
        valid_references = Memo.valid_references(references.data)
        if len(valid_references['invalid']) > 0:
            raise ValidationError(f'Invalid memo references = {valid_references["invalid"]}')
        
        
        
class MemoSearch(FlaskForm):
    title = StringField('Title')
    keywords = StringField('Keywords')
    memo_ref = StringField('Memo')
    username = StringField('User')
    inbox = StringField('Inbox')
    search = SubmitField('Search')

class MemoReportForm(FlaskForm):
    start_date = DateField('Start Date', validators=[DataRequired()])
    end_date = DateField('End Date', validators=[DataRequired()])
    submit = SubmitField('Export CSV')

memos/memos/admin/routes.py
""" ADMIN Routes """
import os
from flask import render_template, url_for, flash, redirect, request, Blueprint, current_app, abort
from flask_login import login_user, current_user, logout_user, login_required
from sqlalchemy import false
from memos import db
from memos.flask_sqlalchemy_txns import transaction
from memos.models.Memo import Memo
from memos.admin.forms import AdminForm

admin = Blueprint('admin', __name__)

@admin.route("/admin", methods=['GET'])
@login_required
def main():
    if current_user.admin == False:
        abort(403)

    with transaction():    
        admin_form = AdminForm()
    return render_template('admin.html', title='Admin',form=admin_form)

@admin.route("/admin/rename",methods = ['POST'])
@login_required
def rename():    
    if current_user.admin == False:
        abort(403)
    
    with transaction():
        admin_form = AdminForm()
        
        if admin_form.validate_on_submit():
            rval = Memo.rename(admin_form.source.data,admin_form.destination.data)
            if rval:
                flash(f'Sucessful rename src = {admin_form.source.data} dst = {admin_form.destination.data}', 'success')
            else:        
                flash(f'Failed to rename source="{admin_form.source.data}" destination="{admin_form.destination.data}"', 'danger')

    return redirect(url_for('admin.main', form=admin_form))



@admin.route("/admin/delete",methods = ['POST'])
@login_required
def delete():
 
    if current_user.admin is False:
        abort(403)

    with transaction():
        admin_form = AdminForm()

        if admin_form.validate_on_submit():
            ref = Memo.parse_reference(admin_form.delete_ref.data)

            current_app.logger.info(f"{ref}")
            if ref["valid"] is True and ref["memo"].cancel(current_user,validate_user=False) is True:
                flash(f'Sucessful delete {admin_form.delete_ref.data}', 'success')
            else:
                flash(f'Failed to delete "{admin_form.delete_ref.data}" invalid reference', 'danger')
 
    return redirect(url_for('admin.main'))

memos/memos/main/routes.py
from flask import render_template, Blueprint, redirect, url_for
from flask import current_app
from memos.models import Memo
import os

from memos.flask_sqlalchemy_txns import transaction

main = Blueprint('main', __name__)

@main.route("/help")
def help():
    with transaction():
        md_text= open(os.path.join(current_app.root_path,"static","doc","help.md"),"r").read()
        return render_template('help.html', config=current_app.config, title='Help', md_text=md_text)


@main.route("/home")
def home():
    with transaction():
        current_app.logger.info(current_app.config['LDAP_HOST'])
        return redirect(url_for("memos.main"))

memos/memos/memos/routes.py
"""
Memo Routes
"""
import csv
from datetime import datetime
from io import StringIO
import os
import re
from memos import db
from flask import (make_response, render_template, url_for, flash,current_app,
                   redirect, request, abort, Blueprint, send_from_directory)
from flask_login import current_user, login_required
from wtforms import SubmitField
from memos.flask_sqlalchemy_txns import transaction

from memos.models.MemoHistory import MemoHistory
from memos.models.User import User
from memos.memos.forms import MemoForm, MemoReportForm, MemoSearch
from memos.models.Memo import Memo
from memos.models.MemoFile import MemoFile
from memos.models.MemoActivity import MemoActivity

memos = Blueprint('memos', __name__)

@memos.route("/")
@memos.route("/memo")
@memos.route("/memo/<username>")
@memos.route("/memo/<username>/<memo_number>")
@memos.route("/memo/<username>/<memo_number>/<memo_version>")
@login_required
def main(username=None,memo_number=None,memo_version=None):
    """ This route is used to display the list of memos """
    with transaction():
        pagesize = User.get_pagesize(current_user)
        page = request.args.get('page', 1, type=int)
        detail = request.args.get('detail')
        showAll = request.args.get('showAll')

        detail = False if detail is None else True
        showAll = False if showAll is None or showAll == 'False' or showAll == '0' else True

        if username is not None and memo_number is None:
            combo = re.split("-",username)
            if len(combo) == 2:
                username = combo[0]
                memo_number = combo[1]
            if len(combo) == 3:
                username = combo[0]
                memo_number = combo[1]
                memo_version = combo[2]

        if memo_number is not None and re.match("^[0-9]+[a-zA-Z]+",memo_number):
            split = re.split("[a-zA-Z]",memo_number)
            memo_version = memo_number[len(split[0]):]
            memo_number = split[0]

        if memo_version is not None:
            memo_version = memo_version.upper()

        if current_user.is_anonymous:
            user = None
        else:
            user = current_user

        memo_list = Memo.get_memo_list(username=username,memo_number=memo_number,
                                    memo_version=memo_version,page=page,pagesize=pagesize,showAll=showAll)

        if len(memo_list.items) == 0:
            flash('No memos match that criteria','danger')

        url_params = {}
        if username:
            url_params['username']=username

        next_page = "memos.main"

        return render_template('memo.html', config=current_app.config,memos=memo_list, title="memo",user=user,delegate=user,
                            signer=None, detail=detail,next_page=next_page,page=page,
                            url_params=url_params,showAll=showAll)


@memos.route("/file/memo/<string:username>/<int:memo_number>/<string:memo_version>/<string:uuid>")
def getfile(username,memo_number,memo_version,uuid):
    """    # this route will return the specified file"""
    with transaction():
        memo = Memo.find(username=username,memo_number=memo_number,memo_version=memo_version)

        if memo is None:
            abort(404)

        if current_user.is_anonymous:
            user = None
        else:
            user = current_user

        if memo.can_access(user,user) is False:
            MemoHistory.activity(memo=memo,memo_activity=MemoActivity.IllegalFile,user=user)
            abort(403)

        current_app.logger.info(f"memo_file = {memo.files}")
        for file in memo.files:
            if file.uuid == uuid:
                directory = os.path.join('static','memos',str(memo.user_id),str(memo_number),
                    memo_version)
                return send_from_directory(directory,file.uuid,download_name=file.filename,
                    as_attachment=False)

        return abort(404)

def process_file(new_memo,formfield):
    """This function will take the formfield, save the file
    into the filesystem at the right place"""
    with transaction():
        if formfield.data:
            f = formfield.data
            # make a directory
            path = new_memo.get_fullpath()
            os.makedirs(path,exist_ok=True)
            mfile = MemoFile(memo_id=new_memo.id,filename=f.filename)
            mfile.save()
            f.save(os.path.join(path, mfile.uuid))

@memos.route("/cu/memo",methods=['GET', 'POST'])
@memos.route("/cu/memo/<string:username>",methods=['GET'])
@memos.route("/cu/memo/<string:username>/<int:memo_number>",methods=['GET', 'POST'])
@login_required
def create_revise_submit(username=None,memo_number=None):
    """The get/post method to create revise and submit new memos"""
    with transaction():
        if username is None:
            username = current_user.username

        # first check to see if the user has permission
        owner = User.find(username=username)

        if owner is None:
            return abort(404)

        delegate = current_user

        if not Memo.can_create(owner=owner,delegate=delegate):
            return abort(403)

        current_app.logger.info(f"owner = {owner} delegate={delegate} memo_number={memo_number}")
        memo = Memo.create_revise(owner=owner,delegate=delegate,memo_number=memo_number)

        class FileForm(MemoForm):
            """# this class is used to add multiple file buttons"""
            @staticmethod
            def create(memo):
                """Create"""
                for idx,_ in enumerate(memo.files):
                    button_name = f"file_{idx}"
                    setattr(FileForm, button_name, SubmitField('Remove'))
            def getField(self, field_name):
                """getField"""
                for f in self:
                    if f.name == field_name:
                        return f
                return None # pragma nocover - This case should never occur


        FileForm.create(memo)
        form = FileForm()

        if request.method == 'GET':
            form.title.data = memo.title
            form.keywords.data = memo.keywords
            form.distribution.data = memo.distribution
            form.signers.data = memo.signers['signers']
            form.confidential.data = memo.confidential
            form.references.data = memo.references['ref_string']

            form.username.data = username
            form.memo_number.data = memo.number
            form.memo_version.data = memo.version

            return render_template('create_memo.html', config=current_app.config,title=f'New Memo {memo}',form=form, legend=f'New Memo {memo}', user=owner, memo=memo)

        # Everthing from here down is POST

        if form.validate_on_submit():
            if form.cancel.data is True:
                return redirect(os.getenv("ENV_URL") + url_for('memos.cancel',username=form.username.data,
                                        memo_number=form.memo_number.data,memo_version=form.memo_version.data))
            
            # Check if signers field is empty
            if not form.signers.data:
                flash("Please enter the initials for your Supervisor in the Signers field.", 'danger')
                return render_template('create_memo.html', config=current_app.config, title=f'New Memo {memo}',
                                       form=form, legend=f'New Memo {memo}', user=delegate, memo=memo)

            memo.title = form.title.data
            memo.distribution = form.distribution.data
            memo.keywords = form.keywords.data
            memo.signers = form.signers.data
            memo.references = form.references.data
            memo.confidential = form.confidential.data

            process_file(memo,form.memodoc1)
            process_file(memo,form.memodoc2)
            process_file(memo,form.memodoc3)
            process_file(memo,form.memodoc4)
            process_file(memo,form.memodoc5)

            # make a json backup
            memo.save()

            # Look and see if they pressed a remove button on one of the files.
            for idx,file in enumerate(memo.files):
                if hasattr(form,f'file_{idx}'):
                    status = getattr(form,f'file_{idx}')
                    if status.data is True:
                        file.remove_file(memo)
                        flash(f"Remove {file}",'success')
                        redirectUrl = request.url.replace('https://0.0.0.0:8086', os.getenv("ENV_URL"))
                        redirectUrl = request.url.replace('https://0.0.0.0:8081', os.getenv("ENV_URL"))
                        return redirect(redirectUrl)  # redirect back to edit instead...

            if form.submit.data is True:
                # submit for sigantures
                if len(memo.files) < 1:
                    flash(f'Must have at least one file attached to Submit memo!', 'danger')
                    redirectUrl = request.url.replace('https://0.0.0.0:8086', os.getenv("ENV_URL"))
                    redirectUrl = request.url.replace('https://0.0.0.0:8081', os.getenv("ENV_URL"))
                    return redirect(redirectUrl)  # redirect back to edit instead...
                memo.process_state(acting=current_user)
                flash(f'{memo} has been created!', 'success')
                return redirect(os.getenv("ENV_URL") + url_for('memos.main'))

            # We are done saving changes
            flash(f'{memo} has been saved!', 'success')
            return redirect(os.getenv("ENV_URL") + url_for('memos.main'))

        return render_template('create_memo.html', config=current_app.config,title=f'New Memo {memo}',
                            form=form, legend=f'New Memo {memo}', user=delegate, memo=memo)


# bring up the list of all of the memos that the current user can sign
@memos.route("/inbox")
@memos.route("/inbox/<string:username>")
@login_required
def inbox(username=None):

memos/memos/templates/admin.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">

        <form method="POST">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <div class="form-group">
                    {% if form.source.errors %}
                        {{ form.source(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.source.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        Source {{ form.source(class="form-control form-control-lg") }} Destination {{ form.destination(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.rename(class="btn btn-outline-info",formaction=url_for("admin.rename")) }}
                </div>
                </fieldset>
            <fieldset class="form-group">
                <div class="form-group">
                    {% if form.source.errors %}
                        {{ form.source(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.source.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        Delete {{ form.delete_ref(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.delete(class="btn btn-outline-info",formaction=url_for("admin.delete")) }}
                </div>
                </fieldset>

            </form>
        
    </div>

{% endblock content %}

memos/memos/templates/auth_error.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
       <p>Authentication error, <a href="/">go back</a></p>
    </div>

{% endblock content %}

memos/memos/templates/help.html
{% extends "layout.html" %}
{% block content %}
{{ md_text|markdown }}
{% endblock content %}

memos/memos/templates/home.html
{% extends "layout.html" %}
{% block content %}
  {% for memo in memos.items %}
    <article class="media content-section">
      <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + memo.user.image_file) }}">
      <div class="media-body">
        <div class="article-metadata">
          <a class="mr-2" href="">{{ memo.user.username }}-{{ memo.number }}-{{ memo.version }}</a>
          <small class="text-muted">{{ memo.memo_date.strftime('%Y-%m-%d') }}</small>
        </div>
        <h2><a class="article-title" href="/memo/{{memo.user.username}}/{{memo.number}}/{{memo.version}}">{{ memo.title }}</a></h2>
      </div>
    </article>
  {% endfor %}
  {% for page_num in memos.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num %}
      {% if memos.page == page_num %}
        <a class="btn btn-info mb-4" href="{{ url_for('memos.main', page=page_num) }}">{{ page_num }}</a>
      {% else %}
        <a class="btn btn-outline-info mb-4" href="{{ url_for('memos.main', page=page_num) }}">{{ page_num }}</a>
      {% endif %}
    {% else %}
      ...
    {% endif %}
    {% endfor %}
{% endblock content %}

memos/memos/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"/>

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}"/>

    {% if title %}
        <title>Memo System - {{ title }}</title>
    {% else %}
        <title>Memo System</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Memo System</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('memos.search') }}">Search</a>
              {% if current_user.admin  %}
              <a class="nav-item nav-link" href="{{ url_for('memos.history') }}">History</a>
              {% endif %}
              <a class="nav-item nav-link" href="{{ url_for('memos.report') }}">Report</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('memos.inbox') }}">Inbox</a>
                <a class="nav-item nav-link" href="{{ url_for('memos.create_revise_submit') }}">New Memo</a>
                <a class="nav-item nav-link" href="{{ url_for('memos.drafts') }}">Drafts</a>
                <a class="nav-item nav-link" href="{{ url_for('memos.main',username=current_user.username) }}?showAll">My Memos</a>
                <a class="nav-item nav-link" href="{{ url_for('memos.template') }}">Template</a>
                
                {% if user and user.admin %}
                    <a class="nav-item nav-link" href="{{ url_for('admin.main') }}">Admin</a>
                {% endif %}
                <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account: {{current_user.username}}</a>
                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                {% if config is not none and 'ENABLE_REGISTER' in config and  config['ENABLE_REGISTER'] == true %}
{#                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>#}
                {% endif %}
              {% endif %}
              <a class="nav-item nav-link" href="{{ url_for('main.help') }}">Help</a>
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

memos/memos/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <style>
        .loginG_container {
            text-align: center;
            width: 215px;
            margin: 0 auto;
            padding: 6px;
            box-shadow: 1px 1px 7px rgba(0, 0, 0, .2);
        }
        .loginG_container a {
            text-decoration: none;
            color: #757575;
            font-size: 13px;
            margin-left: 8px;
        }
    </style>
    <!--Google Login-->
    <div class="card-body" id="login_type-google">
        <div class="loginG_container">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="18px" height="18px"
                 viewBox="0 0 48 48" class="abcRioButtonSvg">
                <g>
                    <path fill="#EA4335"
                          d="M24 9.5c3.54 0 6.71 1.22 9.21 3.6l6.85-6.85C35.9 2.38 30.47 0 24 0 14.62 0 6.51 5.38 2.56 13.22l7.98 6.19C12.43 13.72 17.74 9.5 24 9.5z"></path>
                    <path fill="#4285F4"
                          d="M46.98 24.55c0-1.57-.15-3.09-.38-4.55H24v9.02h12.94c-.58 2.96-2.26 5.48-4.78 7.18l7.73 6c4.51-4.18 7.09-10.36 7.09-17.65z"></path>
                    <path fill="#FBBC05"
                          d="M10.53 28.59c-.48-1.45-.76-2.99-.76-4.59s.27-3.14.76-4.59l-7.98-6.19C.92 16.46 0 20.12 0 24c0 3.88.92 7.54 2.56 10.78l7.97-6.19z"></path>
                    <path fill="#34A853"
                          d="M24 48c6.48 0 11.93-2.13 15.89-5.81l-7.73-6c-2.15 1.45-4.92 2.3-8.16 2.3-6.26 0-11.57-4.22-13.47-9.91l-7.98 6.19C6.51 42.62 14.62 48 24 48z"></path>
                    <path fill="none" d="M0 0h48v48H0z"></path>
                </g>
            </svg>
            <a href="/sign_in">Sign in with Google</a>
        </div>
    </div>
    <!--Google Login END-->
{% endblock content %}

memos/memos/templates/memo.html
{% extends "layout.html" %}
{% block content %}
{% if inbox_list  %}
    Current Inbox: <a class="mr-2" href="{{ url_for('memos.inbox',username=inbox_list[0].username) }}">{{ inbox_list[0].username }}</a> Available Inbox: 
    {% for inbox in inbox_list[1:] %}
      <a class="mr-2" href="{{ url_for('memos.inbox',username=inbox.username) }}">{{ inbox.username }}</a>
    {% endfor %}
{% endif %}

  {% for memo in get_pinned().items %}
  {% include 'memo_template.html'%}
  {% endfor %}
  <hr>

  {% for memo in memos.items %}
  {% if not memo.pinned %}
    {% include 'memo_template.html'%}
    {% endif %}
  {% endfor %}

  {% if memos.items|length == 0 %}
  No Memos Found
  {% endif %}
  {% for page_num in memos.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num %}
      
    {% if memos.page == page_num %}
        <a class="btn btn-info mb-4" href="{{ url_for(next_page, page=page_num, showAll=showAll,**url_params)}}">{{ page_num }}</a>
      {% else %}
        <a class="btn btn-outline-info mb-4" href="{{ url_for(next_page, page=page_num, showAll=showAll,**url_params)}}">{{ page_num }}</a>
   {% endif %}

    {% else %}
      ...
    {% endif %}
    {% endfor %}
      <!-- Modal -->
  <div class="modal fade" id="obsoleteModal" tabindex="-1" role="dialog" aria-labelledby="obsoleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="obsoleteModalLabel">Obsolete Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <-- TODO: ARH -!>
          <form action="{{ url_for('memos.obsolete',username=current_user.username,memo_number=1,memo_version=1) }}" method="POST" onclick="return confirm('Are you sure you want to obsolete this memo?');">
            <input class="btn btn-danger" type="submit" value="Obsolete">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}